# Generated by Django 5.1.4 on 2025-02-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_wishlist'),
    ]

    operations = [
    ]
