# Generated by Django 5.1.4 on 2025-02-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options'),
        ('profiles', '0006_auto_20250222_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wishlist',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
    ]
