# Generated by Django 5.1.4 on 2025-01-12 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
