# Generated by Django 5.1.4 on 2025-01-12 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewbook', '0002_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
    ]
