# Generated by Django 5.1.4 on 2025-01-13 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewbook', '0003_alter_review_options_remove_review_created_at_and_more'),
    ]

    operations = [
    ]
